spring.application.name=compress_project

# Enable multipart uploads
spring.servlet.multipart.enabled=true

# Max file size (single file)
spring.servlet.multipart.max-file-size=50MB

# Max request size (all files together)
spring.servlet.multipart.max-request-size=50MB

# File size threshold
spring.servlet.multipart.file-size-threshold=2KB
